{
  description = "A C- Compiler written for CSCI 435 using LLVM 17";

  inputs = {
    nixpkgs.url = "github:NixOS/nixpkgs/nixos-24.05";
    utils.url = "github:numtide/flake-utils";
  };

  outputs =
    {
      self,
      nixpkgs,
      utils,
    }:
    utils.lib.eachDefaultSystem (
      system:
      let
        pkgs = import nixpkgs { inherit system; };

        llvmPkgs = pkgs.llvmPackages_17;

        cminus = pkgs.stdenv.mkDerivation {
          pname = "CMinus";
          version = "0.1.0";
          src = ./.;

          nativeBuildInputs = [
            pkgs.cmake
            pkgs.doxygen
            llvmPkgs.clang
          ];

          buildInputs = [
            pkgs.boost
            llvmPkgs.llvm
          ];

          cmakeFlags = [
            "-DCMAKE_EXPORT_COMPILE_COMMANDS=1"
          ];

          installPhase = ''
            mkdir -p $out/bin
            cp CMinus $out/bin/
          '';
        };
      in
      {
        packages.default = cminus;

        devShells.default = pkgs.mkShell {
          name = "cminus-dev-shell";

          nativeBuildInputs = [
            pkgs.cmake
            pkgs.ninja
            pkgs.doxygen
            llvmPkgs.clang-tools
            llvmPkgs.clang
          ];

          buildInputs = [
            pkgs.boost
            llvmPkgs.llvm
          ];

          shellHook = ''
            echo "--- C- Compiler Development Environment (LLVM 17) ---"
            echo "Compiler: $(clang --version | head -n 1)"
            echo "Boost:    $(echo ${pkgs.boost.version})"

            # Ensure clangd finds the compile commands generated by CMake
            if [ ! -f compile_commands.json ] && [ -d build ]; then
              ln -s build/compile_commands.json .
            fi
          '';
        };
      }
    );
}
